### ISSUE TITLE
Endless loading while accessing full node or solidity node

### ISSUE THREAD

**Issue by alexkvak** [tronprotocol/docker-tron-quickstart#15]
I'm doing POST request to /walletextension with some body. But it hangs and does not return an answer.

I made rollback to 1.1.4 version (don't know which commit it is) and everything work fine.

Could you fix it?

**Comment by sullof** [comment]
@alexkvak May you update to the version 1.1.16 and let me know if you still have the same problem?

**Comment by alexkvak** [comment]
Yes, I still have the problem, because issue was exactly with 1.1.16. 
I tried once again — it's still there.

Request to `http://localhost:8091/walletextension/gettransactionstothis` hangs

**Comment by sullof** [comment]
It works in my tests with 1.1.16. 
I need more details to try to help. Can you dm me on Monday via Discord?

**Comment by alexkvak** [comment]
@sullof for now `/walletextension/gettransactionstothis` works but `/admin/accounts` responds only on port `9090`, not on `8090`

**Comment by sullof** [comment]
Would you try the new version 1.2.0, please?

**Comment by alexkvak** [comment]
I started but it still `(81) Waiting for sync...`

**Comment by sullof** [comment]
I don't understand it works perfectly when I run it. Can you let me know the command you use to run it, please?
And, please, update to 1.2.1, there was a minor bug in 1.2.0 that I just fixed.

**Comment by alexkvak** [comment]
With 1.2.4 work both endpoints well 👍

**Comment by alexkvak** [comment]
Thanks for your work!

Why do you compile sources from shasta-dev branch instead of download already compiled jar files?

**Comment by sullof** [comment]
The standard java-tron saves data in the blockchain only. To handle events more easily, we need to save them also in an off-chain database. So, we use a modified version of java-tron.
In the future we will use the same version, but we will parse the blocks to get the events' data.
