### ISSUE TITLE
Smart contract web api does not work

### ISSUE THREAD

**Issue by dspecht87** [tronprotocol/docker-tron-quickstart#17]
I followed [Quickstart with TRON Docker][1] from official tron deleopers page to set up a local testnet.

 - Starting tron docker quickstart is successful
 - Deployment of Smart Contract with Tron-Studio is successful
 - Using the contract with Tron-Studio is successful

Using the code from the tutorial I can obtain the contract but when I use a function of the contract the promise times out.

dockerstate.js:

    const TronWeb = require('tronweb');
    const HttpProvider = TronWeb.providers.HttpProvider;
    const fullNode = new HttpProvider('http://127.0.0.1:8090');    //Your local TVM URL  
    const solidityNode = new HttpProvider('http://127.0.0.1:8091');
    const eventServer = 'http://127.0.0.1:8092';
    const privateKey = 'da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0';

    const tronWeb = new TronWeb(
        fullNode,
        solidityNode,
        eventServer,
        privateKey
    );

    async function changestate(){

      let contractAddress = 'TAA6PHMkrQs5bZp7cBYcfdWES9EMb5BZaK';   //Your address
      let contract = await tronWeb.contract().at(contractAddress);
      let resultPost = await contract.postMessage("TRON to the Future").send();
      let resultGet = await contract.getMessage().call();
      console.log('resultGet: ', resultGet);
    }

    changestate()

console output:

    $ node dockerstate.js
    (node:9616) UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded
    at createError (C:\Users\Daniel Specht\Documents\repos\docker-tron-quickstart\app\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (C:\Users\Daniel Specht\Documents\repos\docker-tron-quickstart\app\node_modules\axios\lib\adapters\http.js:216:16)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
    (node:9616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a
     promise which was not handled with .catch(). (rejection id: 2)
    (node:9616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a
    non-zero exit code.

Output on docker console:

    FULL-NODE /wallet/getcontract
    [Output {"bytecode":"608060405234801561001057600080fd5b5061036b806100206000396000f30060806040526004361061004b5763ffffffff7c010000000000000000000000000000000000000000000000000000
    ...  46ac33f208574882cc1a01b78855381ea6bf9978caab7bee73880029","consume_user_resource_percent":100,"name":"HelloWorld","origin_address":"410e93d739dbb8874f599a8bc29c7faefbf8eeab0f","a
    bi":{"entrys":[{"outputs":[{"type":"string"}],"inputs":[{"name":"value","type":"string"}],"name":"postMessage","stateMutability":"Nonpayable","type":"Function"},{"outputs":[{"type":"string"}],"constant":true,"name":"getMessage","stateMutability":"View","type":"Function"},{"inputs":[{"name":"res","type":"uint256"}],"name":"test","type":"Event"}]},"contract_address":"41a6e9867de6f1674a2cadbfbbedd60e0ad63700c8"}
    GET 200 2362 - 3.690 ms
    POST   -  ms

It seems like the smart contract does not work using the web API.
Any suggestions where is the problem and how to solve or debug it?

  [1]: https://developers.tron.network/docs/getting-started-1

**Comment by jonnyhsy** [comment]
+1, same question here https://github.com/tronprotocol/tron-web/issues/114

**Comment by sullof** [comment]
@dspecht87  Same response given to @jonnyhsy 
Instead of 
```
    changestate()
```
call
```
try {
    await changestate()
} catch(err) {
    console.error(err)
}
```

**Comment by dspecht87** [comment]
The 'await' expression is only allowed within an asynchronous function.

It also would not solve the problem that the testnet does not respond.

Some goes for the error catch. It looks cleaner but does not solve the problem.
It is still the same error:

    UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded

**Comment by dspecht87** [comment]
With version 1.1.4 everything works fine

**Comment by jonnyhsy** [comment]
I could confirm what @dspecht87  points, 1.1.4 works fine, starting from 1.1.11 it breaks
