### ISSUE TITLE
Docker manifest missing?

### ISSUE THREAD

**Issue by victor-ponce** [tronprotocol/docker-tron-quickstart#21]
I got this error when trying to download and run quickstart for the first time:

`Unable to find image 'trontools/quickstart:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: manifest for trontools/quickstart:latest not found.`

Command I ran:
`docker run -it --rm -p 9090:9090 --name tron trontools/quickstart`

**Comment by victor-ponce** [comment]
It works if I specify the version, which is currently 1.1.2. So this command works:

`docker run -it --rm -p 9090:9090 --name tron trontools/quickstart:1.1.2`

**Comment by sullof** [comment]
I removed the tag latest because it was creating issues. I have just added it again.
