### ISSUE TITLE
Tron Quickstart listening on http://127.0.0.1:9090  Stop running 

### ISSUE THREAD

**Issue by mingxinyiriyi** [tronprotocol/docker-tron-quickstart#28]
How to solve it?
![image](https://user-images.githubusercontent.com/15307525/51463827-32c09c00-1d9f-11e9-8b6d-f7edc6a57a1d.png)

This information is not available below.

![image](https://user-images.githubusercontent.com/15307525/51463894-60a5e080-1d9f-11e9-96de-3b2d995da38e.png)

**Comment by sullof** [comment]
Sometimes there are syncing issue that are usually solved interrupting the process and running the image again. I guess that this is not the case. Can you provide some more detail, please?

**Comment by mingxinyiriyi** [comment]
It is estimated that the virtual machine has no network connection.
How can I configure windows10?
![image](https://user-images.githubusercontent.com/15307525/51525569-96180000-1e6b-11e9-9de5-b7d9da897814.png)
![image](https://user-images.githubusercontent.com/15307525/51525708-e000e600-1e6b-11e9-8eb4-fb75e0285291.png)
