### ISSUE TITLE
Question: Is there a burn address?

### ISSUE THREAD

**Issue by nibarulabs** [tronprotocol/docker-tron-quickstart#31]
First of all, thank you for doing this. It's amazing and it worked out of the box first time for me. Thank you! (Can't understate that enough, really.)

I am trying to figure out how, though, to get energy so I can execute contracts on my privatenet. I did freeze some trx via the cli wallet no problem. But, this has forced my project to delay contract execution because the given accounts don't seem to have any energy.

I could be totally doing everything wrong, but, I built my small contract and successfully deployed it on the privatenet. When I use another wallet - not the origin deploy wallet - to try to execute that contract, I get an error saying I don't have enough energy, for either wallet.

Through more digging, I found I can freeze (done) or I can burn some trx to get an immediate energy amount. Is there an address I can send trx to on the privatenet to burn the tokens and get some energy.

Thank you!

**Comment by sullof** [comment]
Sorry for being so late with the response.
The private key of Tron Quickstart witness is
da146374a75310b9666e834ee4ad0866d6f4035967bfc76217c5a495fff9f0d0
You can use it to do whatever you like in the private network.
