### ISSUE TITLE
Can not stop/start docker

### ISSUE THREAD

**Issue by andrewsource147** [tronprotocol/docker-tron-quickstart#32]
Hi everyone,
I pull the latest source code and run. Here is my steps:
1. run `docker run -it   -p 9090:9090  --name tron   trontools/quickstart`
(I dont use --rm option because I want to keep my data when stop docker)
2. stop docker when I come home with `docker container stop [container_id]`
3. start docker when I get back to work with `docker container start [container_id]`

After step 3, docker container is running, but I cannot access to my chain anymore. All apis are timeout. Please check my log attachment. Here my version: `{
  "versions": {
    "tron quickstart": "1.2.8",
    "java-tron": "3.2.2"
  }
}`

<img width="1014" alt="screen shot 2019-02-14 at 4 12 09 pm" src="https://user-images.githubusercontent.com/31321699/52775916-4fd14d80-3073-11e9-976c-a854de5311ff.png">
<img width="1045" alt="screen shot 2019-02-14 at 4 07 52 pm" src="https://user-images.githubusercontent.com/31321699/52775744-f23d0100-3072-11e9-8742-dfffd7f3545d.png">

**Comment by titscrypto** [comment]
I have the same issue

**Comment by sullof** [comment]
That was an issue with a missed `}` in the conf file that we fixed in the following version, released immediately after discovering the issue.
