### ISSUE TITLE
Environmental parameters 

### ISSUE THREAD

**Issue by koinov** [tronprotocol/docker-tron-quickstart#42]
Environmental variables don't affect the state of java-tron machine

docker run -it   -p 9090:9090   --rm   --name tron -e "allowSameTokenName=1"  -e "allowTvmTransferTrc10=1" trontools/quickstart

http://127.0.0.1:9090/wallet/getchainparameters returns:
{"chainParameter": [{"key": "getAllowSameTokenName"},{"key": "getAllowTvmTransferTrc10"}]}

Other parameters such as defaultBalance work well. 
Eventron works well when parameters are set for java.tron

**Comment by sullof** [comment]
You are right, they were not manageable because already approved in Mainnet. But there was a problem because they were not actually pre-approved in version < 2.0.5. The recent version 2.0.5 has been configured so that all those proposals are correctly approved. 
Please, use that.

**Comment by koinov** [comment]
It looks like the problem still exists
In your fullnode.conf new options are named 
  getAllowSameTokenName = 1
  getAllowDelegateResource = 1
  getAllowTvmTransferTrc10 = 1
when node is probably looking for:
  allowSameTokenName = 1
  allowDelegateResource = 1
  allowTvmTransferTrc10 = 1

--- I solved it by changing pre-approve.sh in version 2.0.4 that way: 
if [[ $allowTvmTransferTrc10 == '1' ]];then
  echo "Pre-approving allowTvmTransferTrc10e"
  echo "  allowTvmTransferTrc10 = 1" >> /tron/FullNode/fullnode.conf
fi
