### ISSUE TITLE
event-server port for TronWeb

### ISSUE THREAD

**Issue by olegabr** [tronprotocol/docker-tron-quickstart#46]
The `README.md` has this log entry: 

```
--event-server http://127.0.0.1:8060
```

Does it mean that I need to expose the `8060` port and use it for the eventServer in the `TronWeb` object initialization in javascript?

**Comment by sullof** [comment]
Tron Quickstart exposes port 9090. That is all you need. Set TronWeb like
```
new TronWeb({
  fullHost: '127.0.0.1:9090',
  privateKey: ...
})
```
