### ISSUE TITLE
i wonder why i can not get any info about account generated by http://127.0.0.1:8090/admin/accounts-generation

### ISSUE THREAD

**Issue by cheeringsoul** [tronprotocol/docker-tron-quickstart#6]
console output
Available Accounts
==================

(0) TY7tdyPjpRbeYZwR3ZzFAmMoaWupZ26z5b (60000 TRX)
(1) TSAocmSHS3LpWrK1WZnrzSWCh7kTFtkk7B (60000 TRX)
(2) TSGqSgtQcwjfRik47k7kFJD8bZ375vLWPq (60000 TRX)
(3) TCby15YCG97Pq62b2R75KFEWMh7h9Jg5G6 (60000 TRX)
(4) TNCPmFoVhJpRsAkGC9oqpRXJenmnNmJmez (60000 TRX)
(5) TA84p38TNSGtcF8XvRqZnGDnwTjRhXw6Re (60000 TRX)
(6) TNDDrqtym9He5bHyfwEzoExqLznisWU5f8 (60000 TRX)
(7) TUqdooksGGhpkofQYNfyqNuDGFa9rEkLTq (60000 TRX)
(8) TB5Trqvpb1zE9vURYyS6CTPwwdujEKJytn (60000 TRX)
(9) TT5pAwKV5ga9EfMBYKrDHqEmnGtAPhcdHH (60000 TRX)

Private Keys
==================

(0) a0f46af4901c07130bcdbf8902b5e17e944e2c9f0d01729d5c17a0c1bcde1ea9
(1) bdc12c6b1a1d2b0dfbe90eee56617219fef4185384fe3fc0cad8fba4047b7d04
(2) c2f94612dacaa44131d75e398778464d889b2c9e38103ee36571285feeaaa36a
(3) e2b1685d268344c5b90e177a625f1f53aaed2adc615edb62522e9fc885beead9
(4) 830b2f8febb86aa0b68028d875ab16f1d69f06d3f7a9a7b8f2db92e18b8b87b1
(5) 6e50f1317f699f489afc6cda760972dd5fc4c665f84ca7072278d976666beb75
(6) a0c2ebbfd5470da9d21d9a953c1f70aa793bdf25d4b69e1f27e7f81b55638b37
(7) 3c94427793639142c26cf50e224421261fc3fcc07c425fd434b83f1e6eb9cc85
(8) b29005628d007bed60399e0397d61dadf8e90f078788b23701c59345da630ca4
(9) 901016e8b17ea8b24a4921858738c4a9858e969cb2b0cba4af49f6e192da25ac

and I use one of these address , for example TY7tdyPjpRbeYZwR3ZzFAmMoaWupZ26z5b, then decode to hexstring 4D8EED7723E3A516DE619C11DD9CC5026328696BA9676EB3E5B000

then query : 
curl -X POST  http://127.0.0.1:8091/walletsolidity/getaccount -d '{"address": "4D8EED7723E3A516DE619C11DD9CC5026328696BA9676EB3E5B000"}'
and get output:
{}
i can not get balance of that address (60000 TRX), someone please help me..

**Comment by tmao1129** [comment]
@cheeringsoul  I ran that command for my own docker setup, and was able to retrieve the account balance:

$ curl -X POST http://127.0.0.1:8091/walletsolidity/getaccount -d '{"address":"41547b408e153454c316e976e317e54ad0854b4358"}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   160  100   104  100    56    104     56  0:00:01 --:--:--  0:00:01 10000
{"address": "41547b408e153454c316e976e317e54ad0854b4358","balance": 10000000000,"account_resource": {}}

And in my Quickstart Terminal:

(solidity-node) /walletsolidity/getaccount
 {"address": "41547b408e153454c316e976e317e54ad0854b4358","balance": 10000000000,"account_resource": {}}
  POST /walletsolidity/getaccount 200 104 - 3.029 ms

The only thing is, it outputted my balance in units of SUN instead of TRX. I used the default 10,000 TRX. You still running into this issue?

**Comment by tmao1129** [comment]
@cheeringsoul  Also, please join the Developers Discord Channel at https://discordapp.com/invite/GsRgsTD, and also view the developers documents at https://developers.tron.network/. Thanks.

**Comment by tmao1129** [comment]
@cheeringsoul When I decoded the address you used for the API call, into Hex, I instead got: 41F2F72E891AC944AC8FAFB7822BDD7C6DEB6076C3. I think you are using the wrong method to get the Hex String. Please go to https://tronscan.org/#/tools/tron-convert-tool. Click on `Base58Check_HexString`, paste your address in the Base58 box, click `Decode`, and use the outputted HexString. Closing issue.

**Comment by sullof** [comment]
@tmao1129 
The hex of `TY7tdyPjpRbeYZwR3ZzFAmMoaWupZ26z5b` is `41f2f72e891ac944ac8fafb7822bdd7c6deb6076c3`

The address you had is formally incorrect. It must be 42-chars long and starting with `41`.

**Comment by sullof** [comment]
@cheeringsoul 
If you think it can be useful, I can explicitly add to that list the hex version of any address.

**Comment by sullof** [comment]
I will add in a future version a parameter to `http://127.0.0.1:8090/accounts` like `http://127.0.0.1:8090/accounts?format=hex` to returns the addresses in hex format instead than in base58.

**Comment by sullof** [comment]
@cheeringsoul I just pushed `trontools/quickstart:1.1.3` which allows to have the accounts in hex format with the syntax above, or in both formats using `?format=all`. Enjoy it.
